from pydantic import BaseModel

class ResearchQuestion(BaseModel):
    """
    Represents a user research question.

    Attributes:
        question (str): The research question to be answered.
    """
    question: str

class ResearchAnswer(BaseModel):
    """
    Represents an answer generated by the researcher agent.

    Attributes:
        text (str): The answer text.
    """
    text: str

class Feedback(BaseModel):
    """
    Represents feedback from the evaluator agent.

    Attributes:
        accepted (bool): Whether the answer is accepted.
        comments (str): Feedback or suggestions for improvement.
    """
    accepted: bool
    comments: str
